server:
  port: 30401

spring:
  profiles:
    active: dev # 设为开发环境
  main:
    allow-circular-references: true # 为满足部分业务场景，开启循环依赖
  datasource:
    # 配置数据库连接池
    druid:
      driver-class-name: ${glimmer.datasource.driver-class-name}
      url: jdbc:mysql://${glimmer.datasource.host}:${glimmer.datasource.port}/${glimmer.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${glimmer.datasource.username}
      password: ${glimmer.datasource.password}
  servlet: # 配置文件上传大小限制
    multipart:
      max-file-size: 4000MB
      max-request-size: 6000MB
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.glimmer.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

# 设置日志管理
logging:
  level:
    com:
      glimmer:
        mapper: debug
        service: info
        controller: info

glimmer:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    secret-key: as2f6gys3m
    # 设置jwt过期时间 以毫秒计 这里为7天
    ttl: 604800000
    # 设置前端传递过来的令牌名称
    token-name: Authorization

